In [17]:
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from autoviz.AutoViz_Class import AutoViz_Class

In [19]:
data = pd.read_csv("states_all.csv")
data

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,NaN,NaN,731634.0,208.0,252.0,207.0,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,NaN,NaN,122487.0,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,NaN,NaN,673477.0,215.0,265.0,209.0,NaN
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,NaN,NaN,441490.0,210.0,256.0,211.0,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,NaN,NaN,5254844.0,208.0,261.0,202.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,246.0,286.0,227.0,265.0

In [5]:
data.shape

(1715, 25)

In [6]:
data.isnull()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,True,False,True,True,True,True
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1711,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1712,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1713,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
1714,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False

In [7]:
data.isnull().sum()

PRIMARY_KEY                        0
STATE                              0
YEAR                               0
ENROLL                           491
TOTAL_REVENUE                    440
FEDERAL_REVENUE                  440
STATE_REVENUE                    440
LOCAL_REVENUE                    440
TOTAL_EXPENDITURE                440
INSTRUCTION_EXPENDITURE          440
SUPPORT_SERVICES_EXPENDITURE     440
OTHER_EXPENDITURE                491
CAPITAL_OUTLAY_EXPENDITURE       440
GRADES_PK_G                      173
GRADES_KG_G                       83
GRADES_4_G                        83
GRADES_8_G                        83
GRADES_12_G                       83
GRADES_1_8_G                     695
GRADES_9_12_G                    644
GRADES_ALL_G                      83
AVG_MATH_4_SCORE                1150
AVG_MATH_8_SCORE                1113
AVG_READING_4_SCORE             1065
AVG_READING_8_SCORE             1153
dtype: int64

In [8]:
data_1 = data.fillna(value=data['ENROLL'].min())
data_1

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,43866.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,43866.0,43866.0,731634.0,208.0,252.0,207.0,43866.0
1,1992_ALASKA,ALASKA,1992,43866.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,43866.0,43866.0,122487.0,43866.0,43866.0,43866.0,43866.0
2,1992_ARIZONA,ARIZONA,1992,43866.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,43866.0,43866.0,673477.0,215.0,265.0,209.0,43866.0
3,1992_ARKANSAS,ARKANSAS,1992,43866.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,43866.0,43866.0,441490.0,210.0,256.0,211.0,43866.0
4,1992_CALIFORNIA,CALIFORNIA,1992,43866.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,43866.0,43866.0,5254844.0,208.0,261.0,202.0,43866.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,246.0,286.0,227.0,265.0

In [9]:
data_2 = data_1.fillna(method='pad')
data_2

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,43866.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,43866.0,43866.0,731634.0,208.0,252.0,207.0,43866.0
1,1992_ALASKA,ALASKA,1992,43866.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,43866.0,43866.0,122487.0,43866.0,43866.0,43866.0,43866.0
2,1992_ARIZONA,ARIZONA,1992,43866.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,43866.0,43866.0,673477.0,215.0,265.0,209.0,43866.0
3,1992_ARKANSAS,ARKANSAS,1992,43866.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,43866.0,43866.0,441490.0,210.0,256.0,211.0,43866.0
4,1992_CALIFORNIA,CALIFORNIA,1992,43866.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,43866.0,43866.0,5254844.0,208.0,261.0,202.0,43866.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,246.0,286.0,227.0,265.0

In [10]:
data_3 = data_2.fillna(value='0')
data_3

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,43866.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,43866.0,43866.0,731634.0,208.0,252.0,207.0,43866.0
1,1992_ALASKA,ALASKA,1992,43866.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,43866.0,43866.0,122487.0,43866.0,43866.0,43866.0,43866.0
2,1992_ARIZONA,ARIZONA,1992,43866.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,43866.0,43866.0,673477.0,215.0,265.0,209.0,43866.0
3,1992_ARKANSAS,ARKANSAS,1992,43866.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,43866.0,43866.0,441490.0,210.0,256.0,211.0,43866.0
4,1992_CALIFORNIA,CALIFORNIA,1992,43866.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,43866.0,43866.0,5254844.0,208.0,261.0,202.0,43866.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,...,43866.0,43866.0,43866.0,43866.0,43866.0,43866.0,246.0,286.0,227.0,265.0

In [11]:
data_4 = data.fillna({'ENROLL':'77'})
data_4

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,77,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,NaN,NaN,731634.0,208.0,252.0,207.0,NaN
1,1992_ALASKA,ALASKA,1992,77,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,NaN,NaN,122487.0,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,77,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,NaN,NaN,673477.0,215.0,265.0,209.0,NaN
3,1992_ARKANSAS,ARKANSAS,1992,77,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,NaN,NaN,441490.0,210.0,256.0,211.0,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,77,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,NaN,NaN,5254844.0,208.0,261.0,202.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,77,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,77,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,77,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,77,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,77,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,246.0,286.0,227.0,265.0

In [12]:
data_5 = data.fillna(value=data['TOTAL_REVENUE'].min())
data_5

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,465650.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,465650.0,465650.0,731634.0,208.0,252.0,207.0,465650.0
1,1992_ALASKA,ALASKA,1992,465650.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,465650.0,465650.0,122487.0,465650.0,465650.0,465650.0,465650.0
2,1992_ARIZONA,ARIZONA,1992,465650.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,465650.0,465650.0,673477.0,215.0,265.0,209.0,465650.0
3,1992_ARKANSAS,ARKANSAS,1992,465650.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,465650.0,465650.0,441490.0,210.0,256.0,211.0,465650.0
4,1992_CALIFORNIA,CALIFORNIA,1992,465650.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,465650.0,465650.0,5254844.0,208.0,261.0,202.0,465650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,246.0,286.0,227.0,265.0

In [13]:
data_5.isnull().sum()

PRIMARY_KEY                     0
STATE                           0
YEAR                            0
ENROLL                          0
TOTAL_REVENUE                   0
FEDERAL_REVENUE                 0
STATE_REVENUE                   0
LOCAL_REVENUE                   0
TOTAL_EXPENDITURE               0
INSTRUCTION_EXPENDITURE         0
SUPPORT_SERVICES_EXPENDITURE    0
OTHER_EXPENDITURE               0
CAPITAL_OUTLAY_EXPENDITURE      0
GRADES_PK_G                     0
GRADES_KG_G                     0
GRADES_4_G                      0
GRADES_8_G                      0
GRADES_12_G                     0
GRADES_1_8_G                    0
GRADES_9_12_G                   0
GRADES_ALL_G                    0
AVG_MATH_4_SCORE                0
AVG_MATH_8_SCORE                0
AVG_READING_4_SCORE             0
AVG_READING_8_SCORE             0
dtype: int64

In [14]:
data_5.boxplot(column="ENROLL")

In [15]:
plt.figure(figsize=(8,6))
plt.title('Before Scaling')
sns.kdeplot(data['ENROLL'])
sns.kdeplot(data['TOTAL_REVENUE'])
sns.kdeplot(data['FEDERAL_REVENUE'])
sns.kdeplot(data['STATE_REVENUE'])

plt.show()

data_5

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,465650.0,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,465650.0,465650.0,731634.0,208.0,252.0,207.0,465650.0
1,1992_ALASKA,ALASKA,1992,465650.0,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,465650.0,465650.0,122487.0,465650.0,465650.0,465650.0,465650.0
2,1992_ARIZONA,ARIZONA,1992,465650.0,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,465650.0,465650.0,673477.0,215.0,265.0,209.0,465650.0
3,1992_ARKANSAS,ARKANSAS,1992,465650.0,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,465650.0,465650.0,441490.0,210.0,256.0,211.0,465650.0
4,1992_CALIFORNIA,CALIFORNIA,1992,465650.0,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,465650.0,465650.0,5254844.0,208.0,261.0,202.0,465650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1710,2019_VIRGINIA,VIRGINIA,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,247.0,287.0,224.0,262.0
1711,2019_WASHINGTON,WASHINGTON,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,240.0,286.0,220.0,266.0
1712,2019_WEST_VIRGINIA,WEST_VIRGINIA,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,231.0,272.0,213.0,256.0
1713,2019_WISCONSIN,WISCONSIN,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,242.0,289.0,220.0,267.0
1714,2019_WYOMING,WYOMING,2019,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,...,465650.0,465650.0,465650.0,465650.0,465650.0,465650.0,246.0,286.0,227.0,265.0

In [21]:
!pip install autoviz

Requirement already satisfied: autoviz in c:\users\venkata chaitanya\anaconda3\lib\site-packages (0.1.21)
Requirement already satisfied: xlrd in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (2.0.1)
Requirement already satisfied: fsspec>=0.3.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (2021.7.0)
Requirement already satisfied: scikit-learn in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (0.24.2)
Requirement already satisfied: seaborn in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (0.11.1)
Requirement already satisfied: statsmodels in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (0.12.2)
Requirement already satisfied: wordcloud in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (1.8.1)
Requirement already satisfied: jupyter in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (1.0.0)
Requirement already satisfied: hvplot in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (0.7.3)
Requirement already satisfied: ipython in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (7.26.0)
Requirement already satisfied: matplotlib in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (3.4.2)
Requirement already satisfied: holoviews in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (1.14.6)
Requirement already satisfied: pandas in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (1.3.1)
Requirement already satisfied: bokeh in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (2.4.1)
Requirement already satisfied: xgboost in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from autoviz) (1.5.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (5.4.1)
Requirement already satisfied: tornado>=5.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (6.1)
Requirement already satisfied: numpy>=1.11.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (1.20.3)
Requirement already satisfied: pillow>=7.1.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (8.3.1)
Requirement already satisfied: packaging>=16.8 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (21.0)
Requirement already satisfied: Jinja2>=2.9 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (2.11.3)
Requirement already satisfied: typing-extensions>=3.10.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bokeh->autoviz) (3.10.0.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh->autoviz) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from packaging>=16.8->bokeh->autoviz) (2.4.7)
Requirement already satisfied: panel>=0.8.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from holoviews->autoviz) (0.12.4)
Requirement already satisfied: colorcet in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from holoviews->autoviz) (2.0.6)
Requirement already satisfied: param<2.0,>=1.9.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from holoviews->autoviz) (1.12.0)
Requirement already satisfied: pyviz-comms>=0.7.4 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from holoviews->autoviz) (2.1.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from pandas->autoviz) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from pandas->autoviz) (2.8.2)
Requirement already satisfied: tqdm>=4.48.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from panel>=0.8.0->holoviews->autoviz) (4.62.0)
Requirement already satisfied: markdown in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from panel>=0.8.0->holoviews->autoviz) (3.3.4)
Requirement already satisfied: pyct>=0.4.4 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from panel>=0.8.0->holoviews->autoviz) (0.4.8)
Requirement already satisfied: requests in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from panel>=0.8.0->holoviews->autoviz) (2.25.1)
Requirement already satisfied: bleach in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from panel>=0.8.0->holoviews->autoviz) (4.0.0)
Requirement already satisfied: six>=1.5 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->autoviz) (1.16.0)
Requirement already satisfied: colorama in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from tqdm>=4.48.0->panel>=0.8.0->holoviews->autoviz) (0.4.4)
Requirement already satisfied: webencodings in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from bleach->panel>=0.8.0->holoviews->autoviz) (0.5.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (52.0.0.post20210125)
Requirement already satisfied: jedi>=0.16 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (0.17.2)
Requirement already satisfied: pickleshare in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (3.0.17)
Requirement already satisfied: decorator in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (5.0.9)
Requirement already satisfied: backcall in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (0.2.0)
Requirement already satisfied: traitlets>=4.2 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (5.0.5)
Requirement already satisfied: pygments in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (2.9.0)
Requirement already satisfied: matplotlib-inline in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipython->autoviz) (0.1.2)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jedi>=0.16->ipython->autoviz) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->autoviz) (0.2.5)
Requirement already satisfied: ipython-genutils in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from traitlets>=4.2->ipython->autoviz) (0.2.0)
Requirement already satisfied: notebook in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (6.4.1)
Requirement already satisfied: qtconsole in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (5.1.0)
Requirement already satisfied: nbconvert in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (6.1.0)
Requirement already satisfied: ipykernel in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (5.3.4)
Requirement already satisfied: jupyter-console in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (6.4.0)
Requirement already satisfied: ipywidgets in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter->autoviz) (7.6.3)
Requirement already satisfied: jupyter-client in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipykernel->jupyter->autoviz) (6.1.12)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipywidgets->jupyter->autoviz) (1.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipywidgets->jupyter->autoviz) (5.1.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from ipywidgets->jupyter->autoviz) (3.5.1)
Requirement already satisfied: jupyter-core in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->autoviz) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->autoviz) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->autoviz) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->autoviz) (21.2.0)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from notebook->jupyter->autoviz) (1.5.0)
Requirement already satisfied: argon2-cffi in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from notebook->jupyter->autoviz) (20.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from notebook->jupyter->autoviz) (0.9.4)
Requirement already satisfied: pyzmq>=17 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from notebook->jupyter->autoviz) (20.0.0)
Requirement already satisfied: prometheus-client in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from notebook->jupyter->autoviz) (0.11.0)
Requirement already satisfied: pywin32>=1.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets->jupyter->autoviz) (228)
Requirement already satisfied: pywinpty>=0.5 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook->jupyter->autoviz) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from argon2-cffi->notebook->jupyter->autoviz) (1.14.6)
Requirement already satisfied: pycparser in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter->autoviz) (2.20)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from matplotlib->autoviz) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from matplotlib->autoviz) (0.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (1.4.3)
Requirement already satisfied: jupyterlab-pygments in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.1.2)
Requirement already satisfied: testpath in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.5.0)
Requirement already satisfied: defusedxml in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.5.3)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbconvert->jupyter->autoviz) (0.3)
Requirement already satisfied: async-generator in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->autoviz) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->autoviz) (1.5.1)
Requirement already satisfied: qtpy in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from qtconsole->jupyter->autoviz) (1.9.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from requests->panel>=0.8.0->holoviews->autoviz) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from requests->panel>=0.8.0->holoviews->autoviz) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from requests->panel>=0.8.0->holoviews->autoviz) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from requests->panel>=0.8.0->holoviews->autoviz) (1.26.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from scikit-learn->autoviz) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.6.2)
Requirement already satisfied: patsy>=0.5 in c:\users\venkata chaitanya\anaconda3\lib\site-packages (from statsmodels->autoviz) (0.5.1)

In [23]:
from autoviz.AutoViz_Class import AutoViz_Class

AV = AutoViz_Class()

In [20]:
filename = "states_all.csv"
sep = ","
dft = AV.AutoViz(
    filename,
    sep=",",
    depVar="",
    dfte=None,
    header=0,
    verbose=0,
    lowess=False,
    chart_format="svg",
    max_rows_analyzed=150000,
    max_cols_analyzed=30,
)

NameError: name 'AV' is not defined